export const IMAGE_EXT = [
  "jpg",
  "jpeg",
  "png",
  "gif",
  "bmp",
  "webp",
  "ico",
  "tif",
  "tiff",
  "svg",
  "raw",
  "tga",
] as const;

export const VIDEO_EXT = [
  "mp4",
  "m4v",
  "mp4v",
  "3gp",
  "3g2",
  "avi",
  "mov",
  "wmv",
  "mkv",
  "flv",
  "ogv",
  "webm",
  "h264",
  "264",
  "hevc",
  "265",
] as const;

export const AUDIO_EXT = [
  "mp3",
  "wav",
  "ogg",
  "aac",
  "wma",
  "flac",
  "m4a",
] as const;

export const EXT_TO_MIME: Record<string, string> = {
  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  aac: "audio/aac",
  wma: "audio/x-ms-wma",
  flac: "audio/flac",
  m4a: "audio/mp4",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  webp: "image/webp",
  bmp: "image/bmp",
  ico: "image/x-icon",
  tif: "image/tiff",
  tiff: "image/tiff",
  mp4: "video/mp4",
  webm: "video/webm",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  mov: "video/quicktime",
  wmv: "video/x-ms-wmv",
  flv: "video/x-flv",
  ogv: "video/ogg",
  "3gp": "video/3gpp",
  "3g2": "video/3gpp2",
};

export const ACCEPTED_FORMAT = {
  image: {
    "image/jpeg": [".jpg", ".jpeg"],
    "image/png": [".png"],
    "image/gif": [".gif"],
    "image/bmp": [".bmp"],
    "image/webp": [".webp"],
    "image/x-icon": [".ico"],
    "image/tiff": [".tif", ".tiff"],
    "image/svg+xml": [".svg"],
  },
  video: { "video/*": [] },
  audio: { "audio/*": [] },
} as const;
